### ISSUE TITLE
Question about the opensourcecobol4j's support of SQL EXEC, SQLCA and GOBACK statement

### ISSUE THREAD

**Issue by hungpchu** [opensourcecobol/opensourcecobol4j#27]
Hi,
  Does opensourcecobol4j support SQL communication area, SQL EXEC statement and GOBACK statement? I checked in the progress of the development in README file but I do not see the mention of these statements.
<img width="766" alt="Screen Shot 2021-09-07 at 4 30 49 PM" src="https://user-images.githubusercontent.com/25466693/132413521-a20bc12f-1a84-4f60-a3e1-c69cac8db31e.png">

**Comment by ytr-sakamoto** [comment]
opensource COBOL 4j supprots GOBACK statement.

In order to use SQL related features of [opensource COBOL](https://github.com/opensourcecobol/opensource-cobol), you need to use [Open-COBOL-ESQL](https://github.com/opensourcecobol/Open-COBOL-ESQL).
I am developing Open-COBOL-ESQL-4j which enables SQL features of opensource COBOL 4j and will release it within a few months.

**Comment by ytr-sakamoto** [comment]
I released [Open-COBOL-ESQL-4j](https://github.com/opensourcecobol/Open-COBOL-ESQL-4j), the SQL pre-compiler for opensource COBOL 4j.
